# configs/accelerate_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: fp16
num_processes: 4
machine_rank: 0
main_process_ip: null
main_process_port: null
deepspeed_config: {}
